In [2]:
import pandas as pd
import json

In [3]:
# with open('/Users/fabienyah/Documents/1DataScienceProject/5-github/project-made-with-ml/v1_simplest/results.jsonl') as f:
#     result = json.load(f)

In [4]:
df = pd.read_json('/Users/fabienyah/Documents/1DataScienceProject/5-github/project-made-with-ml/v1_simplest/results.jsonl', lines=True)

In [5]:
df = df.round(4)

In [6]:
df

,run_id,roc_auc_mean,accuracy_mean,precision_mean,recall_mean,f1_mean,encoding,binning,feature_set,scaler,model,cv_folds,metric
0,ordinal_by_interval_extended_standard_logreg,0.8480,0.7822,0.7228,0.7016,0.7115,ordinal,by_interval,extended,standard,logreg,5,roc_auc
1,ordinal_by_interval_extended_standard_xgb,0.8462,0.7958,0.7569,0.6901,0.7206,ordinal,by_interval,extended,standard,xgb,5,roc_auc
2,ordinal_by_interval_extended_standard_lgbm,0.8593,0.8115,0.7866,0.6987,0.7383,ordinal,by_interval,extended,standard,lgbm,5,roc_auc
3,ordinal_by_interval_extended_standard_rf,0.8380,0.7935,0.7551,0.6899,0.7192,ordinal,by_interval,extended,standard,rf,5,roc_auc
4,ordinal_by_interval_extended_minmax_logreg,0.8506,0.7890,0.7336,0.7075,0.7195,ordinal,by_interval,extended,minmax,logreg,5,roc_auc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,target_custom_extended_standard_rf,0.8542,0.8092,0.7933,0.6811,0.7283,target,custom,extended,standard,rf,5,roc_auc
68,target_custom_extended_minmax_logreg,0.8494,0.7890,0.7436,0.6900,0.7146,target,custom,extended,minmax,logreg,5,roc_auc
69,target_custom_extended_minmax_xgb,0.8239,0.7733,0.7194,0.6725,0.6947,target,custom,extended,minmax,xgb,5,roc_auc
70,target_custom_extended_minmax_lgbm,0.8524,0.8092,0.7733,0.7105,0.7402,target,custom,extended,minmax,lgbm,5,roc_auc
71,target_custom_extended_minmax_rf,0.8476,0.7935,0.7584,0.6781,0.7147,target,custom,extended,minmax,rf,5,roc_auc

In [7]:
df.sort_values(by='roc_auc_mean', ascending=False)

,run_id,roc_auc_mean,accuracy_mean,precision_mean,recall_mean,f1_mean,encoding,binning,feature_set,scaler,model,cv_folds,metric
10,ordinal_by_frq_extended_standard_lgbm,0.8713,0.8104,0.7844,0.7017,0.7398,ordinal,by_frq,extended,standard,lgbm,5,roc_auc
14,ordinal_by_frq_extended_minmax_lgbm,0.8698,0.8160,0.7909,0.7133,0.7489,ordinal,by_frq,extended,minmax,lgbm,5,roc_auc
46,frequency_custom_extended_minmax_lgbm,0.8696,0.8115,0.7796,0.7106,0.7424,frequency,custom,extended,minmax,lgbm,5,roc_auc
41,frequency_custom_extended_standard_xgb,0.8669,0.8059,0.7604,0.7253,0.7412,frequency,custom,extended,standard,xgb,5,roc_auc
45,frequency_custom_extended_minmax_xgb,0.8669,0.8059,0.7604,0.7253,0.7412,frequency,custom,extended,minmax,xgb,5,roc_auc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,target_by_interval_extended_standard_lgbm,0.8344,0.8003,0.7724,0.6813,0.7223,target,by_interval,extended,standard,lgbm,5,roc_auc
55,target_by_interval_extended_minmax_rf,0.8266,0.7957,0.7775,0.6579,0.7097,target,by_interval,extended,minmax,rf,5,roc_auc
53,target_by_interval_extended_minmax_xgb,0.8241,0.7891,0.7454,0.6872,0.7136,target,by_interval,extended,minmax,xgb,5,roc_auc
69,target_custom_extended_minmax_xgb,0.8239,0.7733,0.7194,0.6725,0.6947,target,custom,extended,minmax,xgb,5,roc_auc
61,target_by_frq_extended_minmax_xgb,0.8190,0.7846,0.7510,0.6578,0.7001,target,by_frq,extended,minmax,xgb,5,roc_auc

In [10]:
df.sort_values(by='accuracy_mean', ascending=False)

,run_id,roc_auc_mean,accuracy_mean,precision_mean,recall_mean,f1_mean,encoding,binning,feature_set,scaler,model,cv_folds,metric
38,frequency_by_frq_extended_minmax_lgbm,0.8667,0.8171,0.7857,0.7221,0.7517,frequency,by_frq,extended,minmax,lgbm,5,roc_auc
26,frequency_by_interval_extended_standard_lgbm,0.8514,0.8160,0.7973,0.6989,0.7434,frequency,by_interval,extended,standard,lgbm,5,roc_auc
14,ordinal_by_frq_extended_minmax_lgbm,0.8698,0.8160,0.7909,0.7133,0.7489,ordinal,by_frq,extended,minmax,lgbm,5,roc_auc
22,ordinal_custom_extended_minmax_lgbm,0.8664,0.8149,0.7907,0.7077,0.7445,ordinal,custom,extended,minmax,lgbm,5,roc_auc
42,frequency_custom_extended_standard_lgbm,0.8662,0.8148,0.7897,0.7076,0.7451,frequency,custom,extended,standard,lgbm,5,roc_auc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24,frequency_by_interval_extended_standard_logreg,0.8506,0.7856,0.7283,0.7045,0.7155,frequency,by_interval,extended,standard,logreg,5,roc_auc
61,target_by_frq_extended_minmax_xgb,0.8190,0.7846,0.7510,0.6578,0.7001,target,by_frq,extended,minmax,xgb,5,roc_auc
56,target_by_frq_extended_standard_logreg,0.8466,0.7845,0.7380,0.6812,0.7082,target,by_frq,extended,standard,logreg,5,roc_auc
0,ordinal_by_interval_extended_standard_logreg,0.8480,0.7822,0.7228,0.7016,0.7115,ordinal,by_interval,extended,standard,logreg,5,roc_auc
69,target_custom_extended_minmax_xgb,0.8239,0.7733,0.7194,0.6725,0.6947,target,custom,extended,minmax,xgb,5,roc_auc

In [ ]:
df.sort_values(by='precision_mean', ascending=False)

,run_id,roc_auc_mean,accuracy_mean,precision_mean,recall_mean,f1_mean,encoding,binning,feature_set,scaler,model,cv_folds,metric
26,frequency_by_interval_extended_standard_lgbm,0.8514,0.8160,0.7973,0.6989,0.7434,frequency,by_interval,extended,standard,lgbm,5,roc_auc
67,target_custom_extended_standard_rf,0.8542,0.8092,0.7933,0.6811,0.7283,target,custom,extended,standard,rf,5,roc_auc
14,ordinal_by_frq_extended_minmax_lgbm,0.8698,0.8160,0.7909,0.7133,0.7489,ordinal,by_frq,extended,minmax,lgbm,5,roc_auc
22,ordinal_custom_extended_minmax_lgbm,0.8664,0.8149,0.7907,0.7077,0.7445,ordinal,custom,extended,minmax,lgbm,5,roc_auc
42,frequency_custom_extended_standard_lgbm,0.8662,0.8148,0.7897,0.7076,0.7451,frequency,custom,extended,standard,lgbm,5,roc_auc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,target_by_interval_extended_standard_logreg,0.8456,0.7890,0.7321,0.7104,0.7205,target,by_interval,extended,standard,logreg,5,roc_auc
28,frequency_by_interval_extended_minmax_logreg,0.8513,0.7879,0.7316,0.7075,0.7184,frequency,by_interval,extended,minmax,logreg,5,roc_auc
24,frequency_by_interval_extended_standard_logreg,0.8506,0.7856,0.7283,0.7045,0.7155,frequency,by_interval,extended,standard,logreg,5,roc_auc
0,ordinal_by_interval_extended_standard_logreg,0.8480,0.7822,0.7228,0.7016,0.7115,ordinal,by_interval,extended,standard,logreg,5,roc_auc
69,target_custom_extended_minmax_xgb,0.8239,0.7733,0.7194,0.6725,0.6947,target,custom,extended,minmax,xgb,5,roc_auc

In [12]:
df.sort_values(by='f1_mean', ascending=False)

,run_id,roc_auc_mean,accuracy_mean,precision_mean,recall_mean,f1_mean,encoding,binning,feature_set,scaler,model,cv_folds,metric
38,frequency_by_frq_extended_minmax_lgbm,0.8667,0.8171,0.7857,0.7221,0.7517,frequency,by_frq,extended,minmax,lgbm,5,roc_auc
9,ordinal_by_frq_extended_standard_xgb,0.8614,0.8137,0.7768,0.7250,0.7493,ordinal,by_frq,extended,standard,xgb,5,roc_auc
13,ordinal_by_frq_extended_minmax_xgb,0.8614,0.8137,0.7768,0.7250,0.7493,ordinal,by_frq,extended,minmax,xgb,5,roc_auc
14,ordinal_by_frq_extended_minmax_lgbm,0.8698,0.8160,0.7909,0.7133,0.7489,ordinal,by_frq,extended,minmax,lgbm,5,roc_auc
34,frequency_by_frq_extended_standard_lgbm,0.8668,0.8137,0.7834,0.7162,0.7466,frequency,by_frq,extended,standard,lgbm,5,roc_auc
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,target_by_frq_extended_standard_logreg,0.8466,0.7845,0.7380,0.6812,0.7082,target,by_frq,extended,standard,logreg,5,roc_auc
64,target_custom_extended_standard_logreg,0.8481,0.7857,0.7441,0.6754,0.7073,target,custom,extended,standard,logreg,5,roc_auc
62,target_by_frq_extended_minmax_lgbm,0.8536,0.7868,0.7516,0.6697,0.7064,target,by_frq,extended,minmax,lgbm,5,roc_auc
61,target_by_frq_extended_minmax_xgb,0.8190,0.7846,0.7510,0.6578,0.7001,target,by_frq,extended,minmax,xgb,5,roc_auc
69,target_custom_extended_minmax_xgb,0.8239,0.7733,0.7194,0.6725,0.6947,target,custom,extended,minmax,xgb,5,roc_auc